const keys = {
  APP_OPEN_ID: '',
  BANNER_ID: '',
  FEATURE_OPEN_ID: '',
  adKeys: [
    'fashion',
    'clothing',
    'game',
    'soccer',
    'football',
    'film',
    'comic',
    'bitcoin',
    'samsung',
    'mobile',
    'iphone',
    'store',
    'tiktok',
    'music',
    'AI',
    'AR',
    'travel',
    'nature',
    'google',
    'drive',
    'pdf',
    'camera',
    'flash',
    'map',
    'wallpaper',
    'news',
    'instagram',
    'facebook',
    'snapchat',
    'roblox',
    'youtube',
    'twitter',
    'tinder',
    'messenger',
    'tik tok',
    'truth social',
    'whatsapp',
    'cash app',
    'discord',
    'netflix',
    'spotify',
    'amazon',
    'google',
    'soundcloud',
    'photo editor',
    'shazam',
    'meeting',
    'movie',
    'mail',
    'weather',
    'video editor',
    'telegram',
  ],
};

export default keys;
