import LocalizedStrings from 'react-localization';

const Languages = new LocalizedStrings({
  en: {
    emailWasUsed: 'That email address is already in use!',
    emailInValid: 'That email address is invalid!',
    changePWSuccess:
      'Change password successfully!. Login to continue using system.',
    changePWFailed: 'Can not change password now. Please try later.',
    currentPWNotCorrect:
      'Your current password is not correct. Please check and try again.',
    haveProblem: 'There was an error, please try again.',
    delete: 'Delete now',
    deleteMessage:
      'Deleting this account means that all data will be deleted and this account can no longer be used.',
    deleteAccount: 'Delete account',
    gpsLocation: 'Current location from GPS',
    pause: 'Pause',
    start: 'Start',
    warning: 'Warning',
    stillNotStart:
      'You are still not start. Please start working before continue.',
    emailOrId: 'Email or ID Number',
    detail: 'Detail',
    login: 'Login',
    noCredit: 'No credit card require',
    password: 'Password',
    remember: 'Remember me',
    forgotPw: 'Forgot password',
    emailRequireLogin: 'Email/Id is require',
    emailRequire: 'Email is require',
    invalidEmail: 'Invalid email address',
    pwRequire: 'Password is require',
    pwLength: 'Password validation is at least 6 character',
    loginFailed: 'Login failed',
    language: 'Language',
    vi: 'Tiếng Việt',
    en: 'English',
    notHaveAccount: "Don't have an account",
    getStarted: 'Get started',
    forgotPwMessage:
      'Password reset link will be sent to your registered email address.',
    enterEmailHere: 'Enter your registered email here',
    success: 'Success',
    failed: 'Failed',
    resetPWSuccessMessage:
      'Reset link was send to your email. Change your password and comeback to SmartRoute.',
    resetPw: 'Reset password',
    yourCompanyId: 'Your company ID',
    optional: 'Optional',
    agreeWith: 'Agree with',
    termAndService: 'Slogcom Term of Services',
    haveAccount: 'Already have an account',
    error: 'Error',
    messageAgree: 'Please agree with Slogcom Term of Services',
    myRoute: 'My Routes',
    duplicateRoute: 'Duplicate route',
    changeRouteName: 'Change route name',
    deleteRoute: 'Delete route',
    addNewRoute: 'Add new Route',
    routeName: 'Route name',
    updateSuccess: 'Update successfully!',
    cancel: 'Cancel',
    add: 'Add',
    save: 'Save',
    duplicate: 'Duplicated',
    routeNameRequire: 'Route name is require',
    route: 'My Route',
    map: 'Map',
    inbox: 'Inbox',
    settings: 'Settings',
    stopList: 'STOP LIST',
    optimizedRoute: 'OPTIMIZED ROUTE',
    completed: 'COMPLETED',
    emptyStopList1: 'Your list of stop here',
    emptyStopList2: 'Add Stop or Shipment to plan your day',
    optimizeFailed: 'Optimization was failed',
    minutes: 'Minutes',
    anyTime: 'Any Time',
    after: 'After',
    before: 'Before',
    optimize: 'Optimize',
    addStop: 'Add Stop',
    addShipment: 'Add Shipment',
    enterLocation: 'Enter Location',
    normal: 'Normal',
    asap: 'ASAP',
    confirm: 'Confirm',
    note: 'Note',
    task: 'Task',
    pickup: 'Pickup',
    delivery: 'Delivery',
    now: 'Now',
    and: 'And',
    arriveBetween: 'Arrive Between',
    timeAtStop: 'Time at Stop',
    weight: 'Weight',
    volume: 'Volume',
    unit: 'Units',
    shipmentWasCreated: 'New Shipment was created successfully.',
    shipmentWasFailed: 'New Shipment was created failed.',
    stopWasCreated: 'New Stop was created successfully',
    stopWasFailed: 'New Stop was created failed',
    finishAdding: 'Finish Adding',
    saveAndNewStop: 'Save & New Stop',
    newShipment: 'New Shipment',
    addDeliveryStop: 'Add Delivery Stop',
    takePhoto: 'Take photo',
    gallery: 'Gallery',
    viewDelivery: 'View Delivery Location',
    viewPickup: 'View Pickup Location',
    removeShipment: 'Remove Shipment?',
    removeShipmentMessage:
      'Remove this stop will also remove other stop in Shipment.',
    remove: 'Remove',
    edit: 'Edit',
    maximumImage: 'You have reached the maximum upload limit.',
    permissionDenied: 'Permission denied',
    permissionDeniedMessage:
      'To continue, give SmartRoute permission access to your Camera/Gallery',
    gotoSettings: 'Go to settings',
    shipmentUpdateSuccess: 'Shipment was updated successfully',
    stopUpdateSuccess: 'Stop was updated successfully',
    headingToStop: 'Heading to this stop',
    errorUnScheduleMsg:
      'This action can not be executed because you have picked up successfully',
    listOptimizeHere: 'Your list of optimized here',
    optimizePlan: 'Optimize your day',
    maxWeight: 'Max weight is ',
    maxVolume: 'Max volume is ',
    reOptimize: 'Re-optimize',
    reOptimizeSub:
      'Re-optimize current route due to traffic, modifications. Route progress remains.',
    fitToExisting: 'Fit new stops into existing route',
    fitToExistingSub:
      'New added stops will be optimized into exiting Route. Route progress remains',
    default: 'Default',
    returnHome: 'Return to Start location',
    runOptimize: 'Run optimization',
    optimizeOption: 'Optimize Options',
    chooseOptionYouNeedMsg: 'Choose which optimize option fit your need.',
    options: 'Options',
    resetRoute: 'Restart Route',
    resetRouteSub: 'All Stop will be reorder. Route progress  will be lost',
    startRoute: 'START ROUTE',
    endRoute: 'END ROUTE',
    questionWhen: 'Where and When you start driving?',
    questionEnd: 'Where and When you end your route?',
    startLocation: 'Start location',
    endLocation: 'End location',
    startTime: 'Start time',
    endTime: 'End time',
    currentLocation: 'Default Address',
    optimizing: 'Optimizing...',
    optimizeRoute: 'Optimize route',
    unScheduleShipment: 'Un-schedule Shipment',
    unScheduleShipmentSub:
      'Un-schedule this stop will also un-schedule other stop in the Shipment.',
    errorMoveShipmentDelivery:
      'Can not move Shipment Delivery location to before Shipment Pickup location',
    errorMoveShipmentPickup:
      'Can not move Shipment Pickup location to after Shipment Delivery location',
    shipment: 'Shipment',
    stop: 'Stop',
    scheduleAt: 'Schedule at',
    navigation: 'Navigation',
    addNote: 'Add note',
    showLess: 'Show less',
    showMore: 'Show more',
    confirmCancelShipment:
      'Cancel Delivery/Pickup Stop is also cancel Pickup/Delivery stop and Shipment',
    cannotOverrideDelivery:
      'Can not override to Delivery Stop before Pickup Stop',
    failedPickup: 'Fail to pickup will mark Delivery stop and shipment as Fail',
    undo: 'Undo',
    override: 'Override',
    arrived: 'Arrived',
    nextStop: 'Next Stop',
    listCompleted: 'Your list of completed here',
    putBack: 'Put back to the Stop list',
    putPickup:
      'Put this Pickup Stop to Stop list also put Delivery Stop to Stop list too.',
    putDelivery:
      'Put this Delivery Stop to Stop list also put Pickup Stop to Stop list too.',
    canceled: 'Canceled',
    listInbox: 'Your list of inbox here',
    listInboxMsg: 'Do not make you missing any notifications',
    changePw: 'Change password',
    setDefaultAddress: 'Set default address',
    defaultSetting: 'Default settings',
    aboutSlogCom: 'About Slogcom',
    vehicle: 'Vehicle',
    vehicleType: 'Vehicle type',
    car: 'Car',
    bike: 'Bike',
    distanceUnit: 'Distance Unit',
    kilometer: 'Kilometers',
    miles: 'Miles',
    stopDefaultType: 'Stop Default type',
    averageSpeed: 'Average speed per hour',
    tapToSetDefault: 'Tap to set your Default Address',
    updateDefaultSettingSuccess:
      'Your default settings was updated successfully',
    currentPw: 'Current password',
    enterCurrentPw: 'Enter current password',
    newPw: 'New password',
    enterNewPw: 'Enter new password',
    confirmPw: 'Confirm password',
    enterConfirmPw: 'Enter confirm password',
    pwNeedMatch: 'Confirm password must be match with new password.',
    logOut: 'Log out',
    otherSetting: 'Other settings',
  },
  vi: {
    gpsLocation: 'Vị trí hiện tại',
    login: 'Đăng nhập',
    password: 'Mật khẩu',
    remember: 'Ghi nhớ',
    forgotPw: 'Quên mật khẩu',
    emailRequireLogin: 'Nhập Email/Id',
    emailRequire: 'Nhập email',
    invalidEmail: 'Email không hợp lệ',
    pwRequire: 'Nhập mật khẩu',
    pwLength: 'Mật khẩu hợp lệ tối thiểu gồm 6 ký tự',
    loginFailed: 'Đăng nhập thất bại',
    language: 'Ngôn ngữ',
    vi: 'Tiếng Việt',
    en: 'English',
    notHaveAccount: 'Chưa có tài khoản',
    getStarted: 'Tạo tài khoản',
    forgotPwMessage:
      'Đường dẫn cài đặt lại mật khẩu sẽ được gửi vào email đã đăng ký của bạn.',
    enterEmailHere: 'Nhập email đã đăng ký',
    success: 'Thành công',
    failed: 'Thất bại',
    resetPWSuccessMessage:
      'Đường dẫn đặt lại mật khẩu đã được gửi tới email của bạn. Đặt lại mật khẩu mới và quay trở lại với SmartRoute.',
    resetPw: 'Đặt lại mật khẩu',
    yourCompanyId: 'Mã công ty',
    optional: 'Không bắt buộc',
    agreeWith: 'Đồng ý với',
    termAndService: 'Điều khoản của Slogcom',
    haveAccount: 'Đã có tài khoản',
    error: 'Lỗi',
    messageAgree: 'Hãy đồng ý với điều khoản của Slogcom trước khi tiếp tục.',
    myRoute: 'DS Tuyến đường',
    duplicateRoute: 'Tạo bản sao',
    changeRouteName: 'Đổi tên tuyến',
    deleteRoute: 'Xoá tuyến đường',
    addNewRoute: 'Thêm tuyến đường',
    routeName: 'Tên tuyến đường',
    cancel: 'Bỏ qua',
    add: 'Thêm',
    save: 'Lưu',
    duplicate: 'Bản sao',
    routeNameRequire: 'Nhập tên tuyến đường',
    route: 'Tuyến đường',
    map: 'Bản đồ',
    inbox: 'Thông báo',
    settings: 'Cài đặt',
    stopList: 'Điểm cần đi',
    optimizedRoute: 'Tuyến tối ưu',
    completed: 'Hoàn thành',
    emptyStopList1: 'Danh sách các điểm cần đi tại đây',
    emptyStopList2: 'Thêm Điểm hoặc Đơn hàng để lập kế hoạch tối ưu',
    optimizeFailed: 'Tối ưu thất bại.',
    minutes: 'Phút',
    anyTime: 'Bất cứ lúc nào',
    after: 'Sau',
    before: 'Trước',
    optimize: 'Tối ưu',
    addStop: 'Thêm điểm',
    addShipment: 'Thêm đơn hàng',
    enterLocation: 'Nhập địa điểm',
    normal: 'Bình thường',
    asap: 'Khẩn cấp',
    confirm: 'Xác nhận',
    note: 'Ghi chú',
    updateSuccess: 'Cập nhật thành công',
    task: 'Tác vụ',
    pickup: 'Lấy hàng',
    delivery: 'Giao hàng',
    now: 'Bây giờ',
    and: 'Đến',
    arriveBetween: 'Trong khoảng',
    timeAtStop: 'Thời gian dừng tại điểm',
    weight: 'Trọng lượng',
    volume: 'Khối lượng',
    unit: 'Đơn vị',
    shipmentWasCreated: 'Đơn hàng mới đã được tạo thành công',
    shipmentWasFailed: 'Đơn hàng mới không thể tạo.',
    stopWasCreated: 'Tác vụ mới đã được tạo thành công',
    stopWasFailed: 'Tác vụ mới không thể tạo',
    finishAdding: 'Hoàn thành',
    saveAndNewStop: 'Lưu và thêm điểm',
    newShipment: 'Thêm đơn hàng',
    addDeliveryStop: 'Thêm điểm giao',
    takePhoto: 'Chụp ảnh',
    gallery: 'Thư viện',
    viewDelivery: 'Xem điểm giao hàng',
    viewPickup: 'Xem điểm lấy hàng',
    removeShipment: 'Xoá đơn hàng?',
    removeShipmentMessage:
      'Xoá đơn hàng này cũng có nghĩa sẽ xoá toàn bộ dữ liệu của đơn hàng',
    remove: 'Xoá',
    edit: 'Sửa',
    maximumImage: 'Bạn đã upload tối đa số file có thể.',
    permissionDenied: 'Từ chối truy cập',
    permissionDeniedMessage:
      'Để tiếp tục hãy cho SmartRoute quyền truy cập vào Máy Ảnh/Bộ sưu tập của bạn',
    gotoSettings: 'Đi đến cài đặt',
    shipmentUpdateSuccess: 'Đơn hàng được cập nhật thành công',
    stopUpdateSuccess: 'Tác vụ được cập nhật thành công',
    headingToStop: 'Điểm đang hướng tới',
    errorUnScheduleMsg:
      'Hành động này không thể thực hiện vì bạn đã lấy hàng thành công.',
    listOptimizeHere: 'Danh sách các điểm đã được tối ưu',
    optimizePlan: 'Giúp bạn tối ưu tuyến đường',
    maxWeight: 'Tải trọng tối đa',
    maxVolume: 'Thể tích tối đa ',
    reOptimize: 'Tối ưu lại',
    fitToExisting: 'Thêm các điểm mới vào tuyến',
    fitToExistingSub:
      'Các điểm thêm mới được tối ưu vào tuyến hiện tại. Tiến độ lộ trình được giữ nguyên',
    default: 'Mặc định',
    returnHome: 'Quay lại điểm bắt đầu',
    runOptimize: 'Thực hiện tối ưu',
    optimizeOption: 'Thiết lập tối ưu',
    chooseOptionYouNeedMsg: 'Lựa chọn thiết lập bạn mong muốn',
    options: 'Lựa chọn',
    resetRoute: 'Tối ưu toàn bộ',
    resetRouteSub:
      'Tất cả các điểm đều được tối ưu lại. Tiến độ lộ trình sẽ bị mất',
    startRoute: 'Bắt đầu tuyến',
    endRoute: 'Kết thúc tuyến',
    questionWhen: 'Địa điểm và thời gian bạn bắt đầu di chuyển?',
    questionEnd: 'Địa điểm và thời gian bạn muốn kế thúc lộ trình?',
    startLocation: 'Điểm bắt đầu',
    endLocation: 'Điểm kết thúc',
    startTime: 'Thời gian bắt đầu',
    endTime: 'Thời gian kết thúc',
    reOptimizeSub:
      'Tối ưu lại tuyến đường hiện tại do tắc đường, thay đổi...Tiến độ lỗ trình được giữ nguyên',
    currentLocation: 'Địa chỉ mặc định',
    optimizing: 'Đang tối ưu...',
    optimizeRoute: 'Tối ưu tuyến đường',
    unScheduleShipment: 'Huỷ lịch trình đơn hàng',
    unScheduleShipmentSub:
      'Thực hiện hành động này sẽ huỷ luôn tác vụ còn lại của đơn hàng',
    errorMoveShipmentDelivery:
      'Không thể đặt điểm giao hàng trước điểm lấy hàng',
    errorMoveShipmentPickup: 'Không thể đặt điểm lấy hàng sau điểm giao hàng',
    shipment: 'Đơn hàng',
    stop: 'Điểm dừng',
    scheduleAt: 'Lịch dự kiến',
    navigation: 'Chỉ đường',
    addNote: 'Thêm ghi chú',
    showLess: 'Hiển thị ít hơn',
    deleteAccount: 'Xoá tài khoản',
    showMore: 'Hiển thị nhiều hơnkhoản',
    confirmCancelShipment:
      'Bỏ qua điểm nhận hàng/giao hàng cũng sẽ bỏ qua điểm giao hàng/nhận hàng.',
    cannotOverrideDelivery:
      'Không thể ghi đè điểm giao hàng trước điểm nhận hàng',
    failedPickup:
      'Đánh dấu trạng thái không thành công cho điểm nhận hàng cũng sẽ đồng thời đánh dấu không thành công cho điểm giao hàng',
    undo: 'Làm lại',
    override: 'Ghi đè',
    delete: 'Xoá ngay',
    arrived: 'Đã đến',
    nextStop: 'Điểm tiếp theo',
    listCompleted: 'Danh sách những điểm đã hoàn thành',
    putBack: 'Đưa trở lại danh sách điểm dừng',
    putPickup:
      'Đưa điểm nhận hàng về danh sách điểm dừng cũng sẽ đưa điểm giao hàng về danh sách điểm dừng.',
    putDelivery:
      'Đưa điểm giao hàng về danh sách điểm dừng cũng sẽ đưa điểm nhận hàng về danh sách điểm dừng',
    canceled: 'Bỏ qua',
    listInbox: 'Danh sách thông báo',
    listInboxMsg: 'Không làm bạn nhỡ bất cứ 1 thông báo nào.',
    changePw: 'Đổi mật khẩu',
    setDefaultAddress: 'Đặt địa chỉ mặc định',
    defaultSetting: 'Cài đặt mặc định',
    aboutSlogCom: 'Thông tin Slogcom',
    vehicle: 'Phương tiện',
    vehicleType: 'Loại phương tiện',
    car: 'Ô tô',
    bike: 'Xe máy',
    distanceUnit: 'Đơn vị khoảng cách',
    kilometer: 'Km',
    miles: 'Dặm',
    stopDefaultType: 'Loại điểm dừng mặc định',
    averageSpeed: 'Tốc độ trung bình',
    tapToSetDefault: 'Chạm để cài đặt địa chỉ mặc định',
    updateDefaultSettingSuccess: 'Cài đặt đã được thiết lập',
    currentPw: 'Mật khẩu hiện tại',
    enterCurrentPw: 'Nhập mật khẩu hiện tại',
    newPw: 'Mật khẩu mới',
    enterNewPw: 'Nhập mật khẩu mới',
    confirmPw: 'Xác nhận mật khẩu',
    enterConfirmPw: 'Nhập xác nhận mật khẩu',
    pwNeedMatch: 'Xác nhận mật khẩu phải trùng với mật khẩu mới',
    logOut: 'Đăng xuất',
    otherSetting: 'Cài đặt khác',
    noCredit: 'Không yêu cầu thẻ thanh toán',
    detail: 'Nội dung',
    emailOrId: 'Email hoặc ID tài khoản',
    pause: 'Tạm dừng',
    start: 'Bắt đầu',
    warning: 'Cảnh báo',
    deleteMessage:
      'Xoá tài khoản này nghĩa là mọi dữ liệu sẽ bị xoá bỏ và không thể nào sử dụng tài khoản này được nữa.',
    stillNotStart: 'Bạn vẫn chưa bắt đầu. Hãy ấn bắt đầu trước khi tiếp tục',
    emailWasUsed: 'Địa chỉ email này đã được sử dụng!',
    emailInValid: 'Địa chỉ email không hợp lệ!',
    changePWSuccess:
      'Đổi mật khẩu thành công! Vui lòng đăng nhập để tiếp tục sử dụng hệ thống.',
    changePWFailed: 'Không thể đổi mật khẩu lúc này. Vui lòng thử lại sau.',
    currentPWNotCorrect:
      'Mật khẩu hiện tại không đúng. Vui lòng kiểm tra và thử lại.',
    haveProblem: 'Có lỗi xảy ra, vui lòng thử lại.',
  },
});

export default Languages;
