import LocalizedStrings from 'react-localization';
const Strings = new LocalizedStrings({
  en: {
    share: 'Share',
    edit: 'Edit',
    save: 'Save to device',
    delete: 'Delete',
    upcoming: 'Upcoming',
    featureUpcoming:
      'Function is being perfected and will be released soonest! Please wait, OK!',
    image: 'Image',
    close: 'Close',
    finish: 'Done',
    cancel: 'Cancel',
    welcomeBack: 'Welcome back to ePhoto!',
    done: 'Done',
    select: 'Select',
    unSelect: 'Unselect',
    fileNotFound: 'File not found',
    ok: 'OK',
    start: 'Take first image',
    previous: 'Previous',
    search: 'Search',
    enterLocation: 'Change location',
    selectDate: 'Select other date',
    permissionDeniedTitle: 'Access to Location Denied',
    permissionDeniedSubTitle:
      'Weather can not detect your location. Please add your location by click Search button',
    openSettings: 'Add location',
    updating: 'Updating',
    feelLike: 'Feel like',
    airQuality: 'Air quality',
    atmospheric: 'Atmospheric',
    humidity: 'Humidity',
    cloudiness: 'Cloudiness',
    windSpeed: 'Wind speed',
    windDirection: 'Wind direction',
    windGust: 'Wind gust',
    toDay: 'Today',
    other: 'Other day',
    tut1Title: 'Welcome to ePhoto',
    tut1Title1: 'The ultimate photo editor!',
    tut1Subtitle:
      'Transform your photos into masterpieces. Edit with filters, stickers, paint, and text. Let your creativity shine',
    next: 'Next',
    tut2Title: 'Discover amazing features',
    tut2Subtitle1: 'Filters',
    tut2Subtitle12: 'Add magic with professionally crafted filters',
    tut2Subtitle2: 'Stickers',
    tut2Subtitle21: 'Make photos fun with trendy stickers',
    tut2Subtitle3: 'Paint and Draw',
    tut2Subtitle31: 'Create artwork directly on photos',
    tut2Subtitle4: 'Text',
    tut2Subtitle41: 'Personalize with stylish text overlays',
    tut3Title: 'Grant permissions for a seamless experience',
    tut3Title1: 'Storage: Save and access edited photos',
    tut3Title2: 'Camera: Capture new photos for editing',
    tut3Title3: 'Photo Gallery: Access existing images for editing',
    tut3Subtitle2:
      'Your privacy matters. We prioritize data security. Unlock the full potential of ePhoto and create and share stunning photos effortlessly.',
    welcome: 'Welcome to ePhoto!',
    welcome2:
      'Please take a photo or select an image you want to edit with ePhoto.',
  },
  vi: {
    start: 'Bắt đầu ngay',
    welcome: 'Chào mừng bạn đến với ePhoto!',
    welcome2:
      'Hãy chụp 1 tấm ảnh hoặc chọn lựa 1 bức ảnh mà bạn muốn chỉnh sửa cùng ePhoto.',
    airQuality: 'Khí hậu',
    feelLike: 'Cảm giác như',
    permissionDeniedTitle: 'Quyền truy cập vị trí bị từ chối',
    permissionDeniedSubTitle:
      'Weather không thể xác định vị trí của bạn. Vui lòng thêm địa điểm của bạn bằng cách nhấn vào nút Search',
    openSettings: 'Thêm địa điểm',
    updating: 'Đang cập nhật',
    atmospheric: 'Áp suất',
    humidity: 'Độ ẩm',
    cloudiness: 'Độ mây',
    windSpeed: 'Tốc độ gió',
    windDirection: 'Hướng gió',
    windGust: 'Gió mạnh',
    toDay: 'Hôm nay',
    other: 'Ngày khác',
    select: 'Chọn',
    unSelect: 'Bỏ chọn',
    fileNotFound: 'Không có dữ liệu',
    ok: 'OK',
    selectDate: 'Chọn ngày khác',
    search: 'Tìm kiếm',
    enterLocation: 'Thay đổi địa điểm',
    tut1Title: 'Chào mừng đến với ePhoto',
    tut1Title1: 'Công cụ chỉnh sửa ảnh tuyệt vời nhất!',
    tut1Subtitle:
      'Biến những bức ảnh của bạn thành kiệt tác. Chỉnh sửa với bộ lọc, nhãn dán, vẽ và văn bản. Hãy để sáng tạo của bạn tỏa sáng!',
    next: 'Tiếp theo',
    tut2Title: 'Khám phá những tính năng tuyệt vời',
    tut2Subtitle1: 'Bộ lọc',
    tut2Subtitle12: 'Thêm ma thuật với bộ lọc được thiết kế chuyên nghiệp',
    tut2Subtitle2: 'Nhãn dán',
    tut2Subtitle21: 'Làm cho ảnh trở nên vui nhộn với những nhãn dán phổ biến',
    tut2Subtitle3: 'Vẽ và Tạo hình',
    tut2Subtitle31: 'Tạo nên tác phẩm nghệ thuật trực tiếp trên ảnh',
    tut2Subtitle4: 'Văn bản',
    tut2Subtitle41: 'Cá nhân hóa với các lớp văn bản thời trang',
    tut3Title: 'Cấp quyền truy cập để trải nghiệm mượt mà',
    previous: 'Trở lại',
    tut3Title1: 'Lưu trữ: Lưu và truy cập các ảnh đã chỉnh sửa dễ dàng',
    tut3Title2: 'Máy ảnh: Chụp ảnh mới để chỉnh sửa',
    finish: 'Xong',
    close: 'Đóng',
    cancel: 'Bỏ qua',
    done: 'Bắt đầu',
    welcomeBack: 'Chào mừng quay trở lại với ePhoto!',
    tut3Title3:
      'Thư viện ảnh: Truy cập vào các hình ảnh hiện có trên thiết bị để chỉnh sửa.',
    image: 'Ảnh',
    upcoming: 'Sắp ra mắt',
    share: 'Chia sẻ',
    edit: 'Sửa',
    save: 'Lưu vào thiết bị',
    delete: 'Xoá',
    featureUpcoming:
      'Chức năng đang được hoàn thiện và sẽ ra mắt sớm nhất! Vui lòng đợi nha!',
    tut3Subtitle2:
      'Chúng tôi coi trọng quyền riêng tư của bạn. Chúng tôi ưu tiên bảo mật dữ liệu. Mở khóa toàn bộ tiềm năng của ePhoto và tạo ra và chia sẻ những bức ảnh tuyệt đẹp một cách dễ dàng.',
  },
});

export default Strings;
